backend:
  name: github
  repo: lisbon1231/folk-orchestra
  branch: main
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
  - label: "Участники"
    name: "Members" 
    folder: "content/members"
    create: true
    slug: "{{fields.name}}_{{fields.role}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
    - { label: "Коллекция", name: "tags", widget: "hidden", default: "members"}
    - { label: "Шаблон", name: "layout", widget: "hidden", default: "members.njk"}
    - { label: "Имя", name: "name", widget: "string"}
    - { label: "Инструмент", name: "instrument", widget: "select", options: ["Балалайка", "Гитара", "Скрипка", "Волынка", "Контрабас", "Фортепиано"], multiple: true }
    - { label: "Роль", name: "role", widget: "select", options: ["Дирижер", "Музыкант", "Солист"], default: "musician", multiple: false }
    - { label: "Работает", name: "works", widget: "select", options: ["да", "нет"], default: "да"}
    - { label: "О человеке", name: "history", widget: "markdown" }
    - { label: "Фото", name: "photo", widget: "image", required: false }
    # - label: "Участник"
    #   name: "participant"
    #   widget: "relation"
    #   required: false
    #   collection: "Events"
    #   value_field: "title"
    #   search_fields: ["title", "date"]
    #   display_fields: ["{{title}} - {{date}}"]
    #   multiple: true

  - label: "Составы"
    name: "Bands" 
    folder: "content/bands"
    create: true
    fields:
    - { label: "Коллекция", name: "tags", widget: "hidden", default: "bands"}
    - { label: "Шаблон", name: "layout", widget: "hidden", default: "bands.njk"}
    - { label: "Название", name: "name", widget: "string"}
    - { 
      label: "Состав",
      name: "band",
      widget: "relation",
      collection: "Members",
      search_fields: ["name"],
      value_field: "name",
      display_fields: ["name"],
      multiple: true
    }    

  - label: "События"
    name: "Events" 
    folder: "content/events"
    create: true
    fields:
    - { label: "Коллекция", name: "tags", widget: "hidden", default: "events"}
    - { label: "Шаблон", name: "layout", widget: "hidden", default: "event.njk"}
    - { label: "Название", name: "title", widget: "string"}
    - { label: "Короткое описание", name: "short_description", widget: "markdown" }
    - { label: "Подробное Описание", name: "full_description", widget: "markdown" }
    - { label: "Место проведения", name: "place", widget: "string" }
    - { label: "Дата", name: "_date", widget: "datetime", date_format: "DD / MM / YYYY", time_format: "", format: "DD dddd gggg" }
    - { label: "Время", name: "time", widget: "datetime", date_format: "", time_format: "HH : mm", format: "HH:mm" }
    - { label: "Афиша", name: "poster", widget: "image", allow_multiple: false, media_folder: "posters" }
    - { label: "Продолжительность", name: "duration", widget: "number", value_type: "float"}
    - { label: "Вход платный", name: "price", widget: "boolean"}
    - { label: "Баннер", name: "banner", widget: "image", allow_multiple: false, media_folder: "banner" }
    - { label: "Репертуар", name: "composers", widget: "list", allow_add: true, field: {label: Произведение, name: composition, widget: text } }
    - { label: "Тэги", name: "eventtags", widget: "list", allow_add: true }
    - {
      label: "Состав",
      name: "band",
      widget: "relation",
      collection: "Bands",
      search_fields: ["name"],
      value_field: "name",
      display_fields: ["name"]
    }    

  - label: "Про оркестр"
    name: "About"
    folder: "content/info"
    create: true
    slug: "info"
    fields: 
    - { label: "Коллекция", name: "tags", widget: "hidden", default: "info"}
    - { label: "Шаблон", name: "layout", widget: "hidden", default: "main"}
    - { label: "Название", name: "title", widget: "string"}
    - { label: "Краткое описание", name: "short_description", widget: "string" }
    - { label: "Среднее описание", name: "middle_description", widget: "markdown" }
    - { label: "Полное описание", name: "long_description", widget: "markdown" }