backend:
  name: github
  repo: lisbon1231/folk-orchestra
  branch: main
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
  - label: "Состав"
    name: "Members" 
    folder: "content/members"
    create: true
    slug: "{{fields.name}}_{{fields.role}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
    - { label: "Имя", name: "name", widget: "string"}
    - { label: "Инструмент", name: "instrument", widget: "select", options: ["guitar", "violen", "balalaika"], multiple: true }
    - { label: "Роль", name: "role", widget: "select", options: ["conductor", "musician"], default: "musician", multiple: true }
    - { label: "Работает", name: "works", widget: "select", options: ["да", "нет"], default: "да"}
    - { label: "О человеке", name: "history", widget: "markdown" }
    - { label: "Фото", name: "photo", widget: "image", required: false }
    - label: "Участник"
      name: "participant"
      widget: "relation"
      required: false
      collection: "Events"
      value_field: "title"
      search_fields: ["title", "date"]
      display_fields: ["{{title}} - {{date}}"]
      multiple: true
  - label: "События"
    name: "Events" 
    folder: "content/events"
    create: true
    fields: 
    - { label: "Название", name: "title", widget: "string"}
    - { label: "Короткое описание", name: "short_description", widget: "markdown" }
    - { label: "Подробное Описание", name: "full_description", widget: "markdown" }
    - { label: "Место проведения", name: "place", widget: "string" }
    - { label: "Дата", name: "date", widget: "datetime", date_format: "DD / MM / YYYY", time_format: "", format: "DD dddd gggg" }
    - { label: "Время", name: "time", widget: "datetime", date_format: "", time_format: "HH : mm", format: "HH:mm" }
    - { label: "Афиша", name: "poster", widget: "image", allow_multiple: false, media_folder: "posters" }
    - { label: "Продолжительность", name: "duration", widget: "number", value_type: "float"}
    - { label: "Вход платный", name: "price", widget: "boolean"}

  - label: "Про оркестр"
    name: "About"
    folder: "content/info"
    create: true
    slug: "info"
    fields: 
    - { label: "Название", name: "title", widget: "string"}
    - { label: "Краткое описание", name: "short_description", widget: "string" }
    - { label: "Среднее описание", name: "middle_description", widget: "markdown" }
    - { label: "Полное описание", name: "long_description", widget: "markdown" }
    - { 
      label: "Events",
      name: "событие",
      widget: "relation",
      collection: "Events",
      search_fields: ["title", "short_description", "full_description", "place"],
      value_field: "title",
      display_fields: ["title"]
    }    