backend:
  name: github
  repo: lisbon1231/folk-orchestra
  branch: main
media_folder: "src/static/uploads"
# publish_mode: editorial_workflow
media_library:
  name: cloudinary
  config:
    cloud_name: lisbon1231
    api_key: 495568362213653
    multiple: true
public_folder: "/uploads"
collections:
  - label: "Альбомы"
    name: "albums"
    folder: "src/data/albums"
    create: true
    slug: "{{fields.name}}"
    fields:
      - {
          label: "Коллекция",
          name: "tags",
          widget: "hidden",
          default: "albums",
        }
      - {
          label: "Шаблон",
          name: "layout",
          widget: "hidden",
          default: "albums.njk",
        }
      - {
          label: "Событие",
          name: "event",
          widget: "relation",
          collection: "Events",
          search_fields: ["title"],
          value_field: "title",
          display_fields: ["title", "_date"],
          multiple: false,
        }
      - { label: "Описание", name: "description", widget: "string" }
      - { label: "Название", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - {
        label: "Постер",
        name: "poster",
        widget: "image",
        allow_multiple: false,
        media_folder: "poster",
      }
      - {
        label: "Media",
        name: "photos",
        widget: "image",
        required: false,
        media_folder: "photos",
        allow_multiple: true,
        media_library: {
          config: {
            multiple: true
          }
        }
      }
  - label: "Ансамбли"
    name: "ensemble"
    folder: "src/data/ensembles"
    create: true
    slug: "{{fields.name}}_{{fields.role}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { name: id, label: Id, widget: generateId }
      - {
          label: "Коллекция",
          name: "tags",
          widget: "hidden",
          default: "ensembles",
        }
      - {
          label: "Шаблон",
          name: "layout",
          widget: "hidden",
          default: "ensembles.njk",
        }
      - { label: "Название", name: "name", widget: "string" }
      - { label: "Город", name: "city", widget: "string" }
      - { label: "Руководитель", name: "owner", widget: "string" }
      - { label: "Информация", name: "history", widget: "markdown" }
      - { label: "Фото", name: "photo", widget: "image", required: false }

  - label: "Музыканты"
    name: "Members"
    folder: "src/data/members"
    create: true
    slug: "{{fields.name}}_{{fields.role}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { name: id, label: Id, widget: generateId }
      - {
          label: "Коллекция",
          name: "tags",
          widget: "hidden",
          default: "members",
        }
      - {
          label: "Шаблон",
          name: "layout",
          widget: "hidden",
          default: "member.njk",
        }
      - { label: "Имя", name: "name", widget: "string" }
      - { label: "Город", name: "city", widget: "string", required: false  }
      - { label: "Член оркестра Шендерева", name: "is_part_of_orchestra", widget: "boolean", default: false, required: false }
      - {
          label: "Роль",
          name: "role",
          widget: "select",
          options: ["Дирижер", "Музыкант", "Вокал"],
          default: "musician",
          multiple: false,
        }
      - {
          label: "Инструмент",
          name: "instrument",
          widget: "select",
          options:
            [
              "Домра прима",
              "Домра альт",
              "Домра бас",
              "Балалайка прима",
              "Балалайка секунда",
              "Балалайка альт",
              "Балалайка к-бас",
              "Баян",
              "Аккордеон",
              "Мандолина",
              "Ударные",
              "Флейта",
              "Гусли",
              "Гитара",
              "Скрипка",
              "Волынка",
              "Контрабас",
              "Фортепиано",
              "Труба",
              "Клавиши"
            ],
          multiple: true,
          required: false
        }
      - {
          label: "Работает",
          name: "works",
          widget: "select",
          options: ["да", "нет"],
          default: "да",
        }
      - { label: "О человеке", name: "history", widget: "markdown", required: false  }
      - { label: "Фото", name: "photo", widget: "image", required: false }

    # - label: "Участник"
    #   name: "participant"
    #   widget: "relation"
    #   required: false
    #   collection: "Events"
    #   value_field: "title"
    #   search_fields: ["title", "date"]
    #   display_fields: ["{{title}} - {{date}}"]
    #   multiple: true

  - label: "Проекты"
    name: "projects"
    folder: "src/data/projects"
    create: true
    slug: "{{fields.id}}"
    fields:
      - { name: id, label: Id, widget: generateId }
      - { label: "Коллекция", name: "tags", widget: "hidden", default: "projects" }
      - {
          label: "Шаблон",
          name: "layout",
          widget: "hidden",
          default: "projects.njk",
        }
      - { label: "Название", name: "title", widget: "string" }
      - {
          label: "Короткое описание",
          name: "short_description",
          widget: "markdown",
        }
      - {
          label: "Подробное Описание",
          name: "body",
          widget: "markdown",
        }
      - { label: "Тэги", name: "eventtags", widget: "list", allow_add: true }
      - {
          label: "Баннер",
          name: "banner",
          widget: "image",
          allow_multiple: false,
          media_folder: "banner",
        }

  - label: "Составы оркеста Шендерева"
    name: "current_band"
    folder: "src/data/current_band"
    create: true
    fields:
      - { name: id, label: Id, widget: generateId }
      - { label: "Коллекция", name: "tags", widget: "hidden", default: "current_band" }
      - { label: "Название", name: "name", widget: "string" }
      - {
          label: "Участники состава",
          name: "participants",
          widget: "relation",
          collection: "Members",
          search_fields: ["name"],
          value_field: "id",
          display_fields: ["name"],
          multiple: true
      }
  - label: "Составы для выступлений"
    name: "Bands"
    folder: "src/data/bands"
    create: true
    fields:
      - { name: id, label: Id, widget: generateId }
      - { label: "Коллекция", name: "tags", widget: "hidden", default: "bands" }
      - {
          label: "Шаблон",
          name: "layout",
          widget: "hidden",
        }
      - { label: "Название", name: "name", widget: "string" }
      - {
          label: "Состав оркеста Шендерева",
          name: "band",
          widget: "relation",
          collection: "current_band",
          search_fields: ["name"],
          value_field: "id",
          display_fields: ["name"],
          multiple: false,
          required: false
        }
      - {
          label: "Пришлашенные ансамбли/оркестры",
          name: "external_ensemble",
          widget: "relation",
          collection: "ensemble",
          search_fields: ["name"],
          value_field: "id",
          display_fields: ["name"],
          multiple: true,
          required: false
        }
      - {
          label: "Одиночные участники",
          name: "participants",
          widget: "relation",
          collection: "Members",
          search_fields: ["name"],
          value_field: "id",
          display_fields: ["name"],
          multiple: true,
          required: false
        }

  - label: "Новости"
    name: "News"
    folder: "src/data/news"
    create: true
    slug: "{{fields.id}}"
    fields:
      - { name: id, label: Id, widget: generateId }
      - { label: "Коллекция", name: "tags", widget: "hidden", default: "news" }
      - { label: "Шаблон", name: "layout", widget: "hidden", default: "news-single.njk" }
      - { label: "Название", name: "title", widget: "string" }
      - { label: "Короткое описание", name: "short_description", widget: "markdown" }
      - { label: "Подробное описание", name: "body", widget: "markdown" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Постер", name: "poster", widget: "image", media_folder: "posters", allow_multiple: false }

  - label: "События"
    name: "Events"
    folder: "src/data/events"
    create: true
    slug: "{{fields.id}}"
    fields:
      - { name: id, label: Id, widget: generateId }
      - {
          label: "Коллекция",
          name: "tags",
          widget: "hidden",
          default: "events",
        }
      - {
          label: "Шаблон",
          name: "layout",
          widget: "hidden",
          default: "event.njk",
        }
      - { label: "Название", name: "title", widget: "string" }
      - {
          label: "Короткое описание",
          name: "short_description",
          widget: "markdown",
        }
      - {
          label: "Подробное Описание",
          name: "body",
          widget: "markdown",
        }
      - label: "Место и время проведения"
        name: "dateTime"
        widget: "list"
        fields:
          - { label: "Место проведения", name: "place", widget: "string" }
          - { label: "Ссылка на мето проведения", name: "placeLink", widget: "string" }
          - {
            label: "Дата",
            name: "_date",
            widget: "datetime",
            # date_format: "DD / MM / YYYY",
            # time_format: "",
            # format: "DD dddd gggg",
          }
          - {
            label: "Время",
            name: "time",
            widget: "datetime",
            date_format: "",
            time_format: "HH : mm",
            format: "HH mm",
          }
      - {
          label: "Афиша",
          name: "poster",
          widget: "image",
          allow_multiple: false,
          media_folder: "posters",
        }
      - {
          label: "Продолжительность",
          name: "duration",
          widget: "number",
          value_type: "float",
          required: false
        }
      - {
          label: "Ограничение по возрасту",
          name: "age",
          widget: "number",
          required: false
        }
      - { label: "Вход платный", name: "price", widget: "boolean", default: false }
      - {
          label: "Репертуар",
          name: "compositions",
          widget: "list",
          allow_add: true,
          field: { label: Произведение, name: composition, widget: string },
        }
      - label: "Композиторы"
        name: "composers"
        widget: "list"
        fields:
          - { label: Композитор, name: composer, widget: string }
          - { label: "Ссылка на инфромацию о композиторе", name: "link", widget: "string" }
      - { label: "Тэги", name: "eventtags", widget: "list", allow_add: true }
      - {
          label: "Состав",
          name: "band",
          widget: "relation",
          collection: "Bands",
          search_fields: ["name"],
          value_field: "name",
          display_fields: ["name"],
        }
      - {
          label: "Баннер",
          name: "banner",
          widget: "image",
          allow_multiple: false,
          media_folder: "banner",
        }

  - label: "Про оркестр"
    name: "About"
    folder: "src/data"
    create: true
    slug: "index"
    fields:
      - { name: id, label: Id, widget: generateId }
      - { label: "Коллекция", name: "tags", widget: "hidden", default: "info" }
      - { label: "Шаблон", name: "layout", widget: "hidden", default: "index" }
      - { label: "Название", name: "title", widget: "string" }
      - {
          label: "Краткое описание",
          name: "short_description",
          widget: "string",
        }
      - {
          label: "Среднее описание",
          name: "middle_description",
          widget: "markdown",
        }
      - {
          label: "Полное описание",
          name: "long_description",
          widget: "markdown",
        }
  - label: "В честь"
    name: "inhonor"
    folder: "src/data/history"
    create: true
    slug: "inhonor"
    fields:
      - { name: id, label: Id, widget: generateId }
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "О человеке", name: "body", widget: "markdown" }
      - { label: "Главное фото", name: "mainphoto", widget: "image", allow_multiple: false }
      - { label: "Цитаты", name: "quotes", widget: "string" }
      - { label: "Картинки", name: "images", widget: "image", allow_multiple: true }
  - label: "История"
    name: "history"
    folder: "src/data"
    create: true
    slug: "history"
    fields:
      - { name: id, label: Id, widget: generateId }
      - { label: "Коллекция", name: "tags", widget: "hidden", default: "history" }
      - { label: "Шаблон", name: "layout", widget: "hidden", default: "article.njk" }
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "История", name: "body", widget: "markdown" }
      - { label: "Картинки", name: "images", widget: "image", allow_multiple: true }
